// <auto-generated />
using System;
using AirlineBookingsProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirlineBookingsProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510151242_SyncFix")]
    partial class SyncFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirlineBookingsProject.Models.Booking", b =>
                {
                    b.Property<string>("BookingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BookingId");

                    b.HasIndex("FlightId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = "B001",
                            BookingDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightId = "F001",
                            Status = "Confirmed",
                            UserId = "U001"
                        },
                        new
                        {
                            BookingId = "B002",
                            BookingDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightId = "F002",
                            Status = "Confirmed",
                            UserId = "U002"
                        },
                        new
                        {
                            BookingId = "B003",
                            BookingDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightId = "F003",
                            Status = "Cancelled",
                            UserId = "U003"
                        },
                        new
                        {
                            BookingId = "B004",
                            BookingDate = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightId = "F004",
                            Status = "Confirmed",
                            UserId = "U004"
                        },
                        new
                        {
                            BookingId = "B005",
                            BookingDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightId = "F005",
                            Status = "Pending",
                            UserId = "U001"
                        });
                });

            modelBuilder.Entity("AirlineBookingsProject.Models.Flight", b =>
                {
                    b.Property<string>("FlightId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<string>("ToCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlightId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = "F001",
                            Date = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNo = "EK202",
                            FromCity = "Abu Dhabi",
                            Price = 1500.0,
                            Time = new TimeSpan(0, 10, 0, 0, 0),
                            ToCity = "London"
                        },
                        new
                        {
                            FlightId = "F002",
                            Date = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNo = "EY301",
                            FromCity = "Dubai",
                            Price = 900.0,
                            Time = new TimeSpan(0, 7, 0, 0, 0),
                            ToCity = "Cairo"
                        },
                        new
                        {
                            FlightId = "F003",
                            Date = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNo = "QR105",
                            FromCity = "Doha",
                            Price = 2000.0,
                            Time = new TimeSpan(0, 9, 0, 0, 0),
                            ToCity = "Paris"
                        },
                        new
                        {
                            FlightId = "F004",
                            Date = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNo = "BA450",
                            FromCity = "London",
                            Price = 2500.0,
                            Time = new TimeSpan(0, 2, 0, 0, 0),
                            ToCity = "New York"
                        },
                        new
                        {
                            FlightId = "F005",
                            Date = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNo = "LH700",
                            FromCity = "Frankfurt",
                            Price = 3000.0,
                            Time = new TimeSpan(0, 11, 0, 0, 0),
                            ToCity = "Tokyo"
                        });
                });

            modelBuilder.Entity("AirlineBookingsProject.Models.Passenger", b =>
                {
                    b.Property<string>("PassengerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PassengerId");

                    b.HasIndex("BookingId");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            PassengerId = "P001",
                            BookingId = "B001",
                            FullName = "Ali Ahmed",
                            Nationality = "UAE",
                            PassportNo = "A1234567"
                        },
                        new
                        {
                            PassengerId = "P002",
                            BookingId = "B002",
                            FullName = "Sara Khan",
                            Nationality = "India",
                            PassportNo = "B2345678"
                        },
                        new
                        {
                            PassengerId = "P003",
                            BookingId = "B003",
                            FullName = "John Smith",
                            Nationality = "UK",
                            PassportNo = "C3456789"
                        },
                        new
                        {
                            PassengerId = "P004",
                            BookingId = "B004",
                            FullName = "Fatima Noor",
                            Nationality = "UAE",
                            PassportNo = "D4567890"
                        },
                        new
                        {
                            PassengerId = "P005",
                            BookingId = "B005",
                            FullName = "Ali Ahmed",
                            Nationality = "UAE",
                            PassportNo = "E5678901"
                        });
                });

            modelBuilder.Entity("AirlineBookingsProject.Models.Payment", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = "PAY001",
                            Amount = 1500.0,
                            BookingId = "B001",
                            Method = "Card",
                            PaymentDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentId = "PAY002",
                            Amount = 900.0,
                            BookingId = "B002",
                            Method = "Cash",
                            PaymentDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentId = "PAY003",
                            Amount = 2000.0,
                            BookingId = "B003",
                            Method = "Card",
                            PaymentDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentId = "PAY004",
                            Amount = 2500.0,
                            BookingId = "B004",
                            Method = "Card",
                            PaymentDate = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentId = "PAY005",
                            Amount = 3000.0,
                            BookingId = "B005",
                            Method = "Cash",
                            PaymentDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AirlineBookingsProject.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPhoto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "U001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "071f036e-a25f-4d35-95e9-524b1a8d5dd5",
                            Email = "ali@mail.com",
                            EmailConfirmed = false,
                            FullName = "Ali Ahmed",
                            LockoutEnabled = false,
                            Password = "1234",
                            PhoneNumber = "0501111111",
                            PhoneNumberConfirmed = false,
                            Role = "User",
                            SecurityStamp = "d47ee656-4bcf-46f4-a05c-8048e8dad200",
                            TwoFactorEnabled = false,
                            UserPhoto = "noimage.jpg"
                        },
                        new
                        {
                            Id = "U002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1e43b2f5-96f4-4aaa-a2fc-10cb69274dcb",
                            Email = "sara@mail.com",
                            EmailConfirmed = false,
                            FullName = "Sara Khan",
                            LockoutEnabled = false,
                            Password = "1234",
                            PhoneNumber = "0502222222",
                            PhoneNumberConfirmed = false,
                            Role = "User",
                            SecurityStamp = "5bb3d455-704d-4e4d-8481-dc20bbc0decb",
                            TwoFactorEnabled = false,
                            UserPhoto = "noimage.jpg"
                        },
                        new
                        {
                            Id = "U003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e9304d95-1c2a-4632-b497-06e5d38c171d",
                            Email = "john@mail.com",
                            EmailConfirmed = false,
                            FullName = "John Smith",
                            LockoutEnabled = false,
                            Password = "1234",
                            PhoneNumber = "0503333333",
                            PhoneNumberConfirmed = false,
                            Role = "User",
                            SecurityStamp = "d2d5fde0-1fdf-462e-8f4f-bbd037112ff0",
                            TwoFactorEnabled = false,
                            UserPhoto = "noimage.jpg"
                        },
                        new
                        {
                            Id = "U004",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1f16995c-933e-4e14-9f1b-ad0d14f39e9f",
                            Email = "fatima@mail.com",
                            EmailConfirmed = false,
                            FullName = "Fatima Noor",
                            LockoutEnabled = false,
                            Password = "1234",
                            PhoneNumber = "0504444444",
                            PhoneNumberConfirmed = false,
                            Role = "User",
                            SecurityStamp = "edc72cba-d85c-4f73-b92b-2842bf925186",
                            TwoFactorEnabled = false,
                            UserPhoto = "noimage.jpg"
                        },
                        new
                        {
                            Id = "U005",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "899a0070-53eb-4473-8656-5a1feea1dcde",
                            Email = "admin@mail.com",
                            EmailConfirmed = false,
                            FullName = "Admin User",
                            LockoutEnabled = false,
                            Password = "admin",
                            PhoneNumber = "0505555555",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "ab05d5ee-c815-4fb9-8aba-c03b67489b04",
                            TwoFactorEnabled = false,
                            UserPhoto = "noimage.jpg"
                        });
                });

            modelBuilder.Entity("AirlineBookingsProject.Models.Booking", b =>
                {
                    b.HasOne("AirlineBookingsProject.Models.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirlineBookingsProject.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirlineBookingsProject.Models.Passenger", b =>
                {
                    b.HasOne("AirlineBookingsProject.Models.Booking", "Booking")
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("AirlineBookingsProject.Models.Payment", b =>
                {
                    b.HasOne("AirlineBookingsProject.Models.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("AirlineBookingsProject.Models.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("AirlineBookingsProject.Models.Booking", b =>
                {
                    b.Navigation("Passengers");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("AirlineBookingsProject.Models.Flight", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("AirlineBookingsProject.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
